from enum import Enum 

# Clase de las categorias: Enumeración de los tokens (listado de tokens)
class Categoria(Enum):
    NO_RECONOCIDO = "NO RECONOCIDO"
    ENTERO = "ENTERO"
    DECIMAL = "DECIMAL"
    HEXADECIMAL = "HEXADECIMAL"
    IDENTIFICADOR = "IDENTIFICADOR"
    PALABRA_RESERVADA = "PALABRA RESERVADA"
    CADENA_CARACTERES = "CADENA CARACTERES"
    COMENTARIO = "COMENTARIO"
    OPERADOR_ARITMETICO = "OPERADOR ARITMETICO"
    OPERADOR_RELACIONAL = "OPERADOR RELACIONAL"
    OPERADOR_LOGICO = "OPERADOR_LOGICO"
    OPERADOR_INCREMENTODECREMENTO = "OPERADOR INCREMENTO/DECREMENTO"
    OPERADOR_ASIGNACION = "OPERADOR ASIGNACION"
    FIN_SENTENCIA = "FIN SENTENCIA"
    SEPARADOR = "SEPARADOR"
    APERTURA_CIERRE = "APERTURA CIERRE"

    def getString(self):
        return self.value